package com.tuitionexpense.model;

import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity     // marks this class as an entity, meaning that we intend to map this class to a table
@Table(name = "expense", schema = "expenses")

public class Expense {

	
	
	@Id   // used to denote that it is a primary key on this table
	@Column(name = "expense_id")
	// specifies that this field value is generated by a sequence i.e the serial datatype in postgres has an underlying sequence to generate
	// the next value which should be inserted on our table in this column
//	@GeneratedValue(generator = "expense_id_seq", strategy = GenerationType.AUTO)
//	@SequenceGenerator(allocationSize = 1,  name = "expense_id_seq", sequenceName = "expense_id_seq")
	
	private int expenseId;
	@Column(name = "employee_id")
	private long employeeId;
	@Column(name = "expense_image")
	private String expenseImage;
	@Column(name = "status")
	private String status;
	@Column(name = "submission_date")
	private LocalDate submissionDate;
	@Column(name = "details")
	private String details;
	@Column(name = "comments")
	private String comments;
	@Column(name = "amount")
	private long amount;
	@Column(name = "authorized_by")
	private String authorizedBy;
	
	public Expense() {
		super();
		
	}
	
	

	public Expense(String status, String details, long amount) {
		super();
		this.status = status;
		this.details = details;
		this.amount = amount;
	}



	public Expense(long employeeId, String expenseImage, String status, LocalDate submissionDate, String details,
			String comments, long amount, String authorizedBy) {
		super();
		this.employeeId = employeeId;
		this.expenseImage = expenseImage;
		this.status = status;
		this.submissionDate = submissionDate;
		this.details = details;
		this.comments = comments;
		this.amount = amount;
		this.authorizedBy = authorizedBy;
	}



	public Expense(int expenseId, long employeeId, String expenseImage, String status, LocalDate submissionDate,
			String details, String comments, long amount, String authorizedBy) {
		super();
		this.expenseId = expenseId;
		this.employeeId = employeeId;
		this.expenseImage = expenseImage;
		this.status = status;
		this.submissionDate = submissionDate;
		this.details = details;
		this.comments = comments;
		this.amount = amount;
		this.authorizedBy = authorizedBy;
	}



	public int getExpenseId() {
		return expenseId;
	}



	public void setExpenseId(int expenseId) {
		this.expenseId = expenseId;
	}



	public long getEmployeeId() {
		return employeeId;
	}



	public void setEmployeeId(long employeeId) {
		this.employeeId = employeeId;
	}



	public String getExpenseImage() {
		return expenseImage;
	}



	public void setExpenseImage(String expenseImage) {
		this.expenseImage = expenseImage;
	}



	public String getStatus() {
		return status;
	}



	public void setStatus(String status) {
		this.status = status;
	}



	public LocalDate getSubmissionDate() {
		return submissionDate;
	}



	public void setSubmissionDate(LocalDate submissionDate) {
		this.submissionDate = submissionDate;
	}



	public String getDetails() {
		return details;
	}



	public void setDetails(String details) {
		this.details = details;
	}



	public String getComments() {
		return comments;
	}



	public void setComments(String comments) {
		this.comments = comments;
	}



	public long getAmount() {
		return amount;
	}



	public void setAmount(long amount) {
		this.amount = amount;
	}



	public String getAuthorizedBy() {
		return authorizedBy;
	}



	public void setAuthorizedBy(String authorizedBy) {
		this.authorizedBy = authorizedBy;
	}



	@Override
	public String toString() {
		return "Expenses [expenseId=" + expenseId + ", employeeId=" + employeeId + ", expenseImage=" + expenseImage
				+ ", status=" + status + ", submissionDate=" + submissionDate + ", details=" + details + ", comments="
				+ comments + ", amount=" + amount + ", authorizedBy=" + authorizedBy + "]";
	}



}
